/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * one.java
 *
 * Created on Aug 3, 2012, 6:36:09 AM
 */



package project;

//import java.beans.Statement;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


/**
 *
 * @author bilal
 */
public class Addpatient extends javax.swing.JFrame {

    
    
    /** Creates new form one */
    public Addpatient() {
        initComponents();
    }
    DateFormat date=new SimpleDateFormat("dd/MM/yyyy ");
 Date date1=new Date();
    String radiotext="",b,s="",a,st,st1,str,radiotext2="",radiotext3="";
    private void group(){
        group.add(radio1);
        group.add(radio2);
        group2.add(radio3);
        group2.add(radio4);
        group2.add(radio5);
        group3.add(radio6);
        group3.add(radio7);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        group3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txt6 = new javax.swing.JButton();
        txt5 = new javax.swing.JButton();
        txt3 = new javax.swing.JButton();
        txt2 = new javax.swing.JButton();
        txt1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        radio5 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        txt_6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txt_8 = new javax.swing.JTextField();
        txt_9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        City = new javax.swing.JComboBox();
        country = new javax.swing.JComboBox();
        txt_4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        com4 = new javax.swing.JComboBox();
        com2 = new javax.swing.JComboBox();
        com1 = new javax.swing.JComboBox();
        txtt = new javax.swing.JTextField();
        radio6 = new javax.swing.JRadioButton();
        radio7 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        doc = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Patient");
        setForeground(java.awt.Color.gray);
        setResizable(false);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/schedue1.PNG"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.setMaximumSize(new java.awt.Dimension(97, 73));
        jButton1.setMinimumSize(new java.awt.Dimension(72, 73));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/schedu2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/log.JPG"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setBorderPainted(false);
        jButton6.setMaximumSize(new java.awt.Dimension(97, 73));
        jButton6.setMinimumSize(new java.awt.Dimension(72, 73));
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/gut3.JPG"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/billing1.JPG"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setBorderPainted(false);
        jButton5.setMaximumSize(new java.awt.Dimension(97, 73));
        jButton5.setMinimumSize(new java.awt.Dimension(72, 73));
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/billing.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt6.setBackground(new java.awt.Color(0, 0, 0));
        txt6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sear.JPG"))); // NOI18N
        txt6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt6.setBorderPainted(false);
        txt6.setMaximumSize(new java.awt.Dimension(97, 73));
        txt6.setMinimumSize(new java.awt.Dimension(72, 73));
        txt6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sear1.JPG"))); // NOI18N
        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });

        txt5.setBackground(new java.awt.Color(0, 0, 0));
        txt5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Report1.JPG"))); // NOI18N
        txt5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt5.setBorderPainted(false);
        txt5.setMaximumSize(new java.awt.Dimension(97, 73));
        txt5.setMinimumSize(new java.awt.Dimension(72, 73));
        txt5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/reports2.png"))); // NOI18N
        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });

        txt3.setBackground(new java.awt.Color(0, 0, 0));
        txt3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Doctor1.JPG"))); // NOI18N
        txt3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt3.setBorderPainted(false);
        txt3.setMaximumSize(new java.awt.Dimension(97, 73));
        txt3.setMinimumSize(new java.awt.Dimension(72, 73));
        txt3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/doctor2.png"))); // NOI18N
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });

        txt2.setBackground(new java.awt.Color(0, 0, 0));
        txt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Edited add.JPG"))); // NOI18N
        txt2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt2.setBorderPainted(false);
        txt2.setMaximumSize(new java.awt.Dimension(97, 73));
        txt2.setMinimumSize(new java.awt.Dimension(72, 73));
        txt2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/cpyadd.JPG"))); // NOI18N
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        txt1.setBackground(new java.awt.Color(0, 0, 0));
        txt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Copy of 3.jpg"))); // NOI18N
        txt1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt1.setBorderPainted(false);
        txt1.setMaximumSize(new java.awt.Dimension(97, 73));
        txt1.setMinimumSize(new java.awt.Dimension(72, 73));
        txt1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/project/add 3.JPG"))); // NOI18N
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Contact1.JPG"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11));
        jLabel4.setText("Welcome Adminstrator");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/edited.JPG"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo.gif"))); // NOI18N

        jLabel9.setText("Gender :");

        txt_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_1FocusLost(evt);
            }
        });

        jLabel10.setText("Last Name :");

        jLabel11.setText("First Name :");

        txt_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_3FocusLost(evt);
            }
        });

        jLabel12.setText("DOB :");

        jLabel14.setText("City :");

        jLabel15.setText("Country :");

        group2.add(radio5);
        radio5.setText("Other");
        radio5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radio5FocusGained(evt);
            }
        });

        group2.add(radio3);
        radio3.setText("Single");
        radio3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radio3FocusGained(evt);
            }
        });

        group2.add(radio4);
        radio4.setText("Married");
        radio4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radio4FocusGained(evt);
            }
        });

        jLabel16.setText("Maritial Status :");

        txt_6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_6FocusLost(evt);
            }
        });

        jLabel17.setText("Phone :");

        txt_7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_7FocusLost(evt);
            }
        });

        jLabel18.setText("Mobile :");

        txt_8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_8FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_8FocusLost(evt);
            }
        });

        txt_9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_9FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_9FocusLost(evt);
            }
        });

        jLabel19.setText("Email :");

        group.add(radio1);
        radio1.setText("Male");
        radio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radio1FocusGained(evt);
            }
        });

        group.add(radio2);
        radio2.setText("Female");
        radio2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radio2FocusGained(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/delete-2.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\xterme\\Desktop\\Hospital Management System\\new Icons\\Add2.png")); // NOI18N
        jButton3.setText("Insert");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel21.setText("Address :");

        City.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select City" }));
        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        City.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CityFocusGained(evt);
            }
        });

        country.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Country", "America", "Afghanistan", "Bangladesh", "Canada", "Pakistan", "India" }));
        country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryActionPerformed(evt);
            }
        });
        country.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                countryFocusGained(evt);
            }
        });

        txt_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_4FocusLost(evt);
            }
        });

        jLabel13.setText("Patient ID :");

        txt_5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_5FocusLost(evt);
            }
        });

        jLabel23.setText("Prefix :");

        jLabel5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel5PropertyChange(evt);
            }
        });

        com4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1951", "1952", "1953", "1954", "1958", "1960", "1962", "1964", "1966", "1980", "1985", "1990", "1991", "1993", "1995", "1998", "2000", "2002", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012" }));
        com4.setAlignmentX(0.0F);
        com4.setAlignmentY(0.0F);

        com2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        com2.setAlignmentX(0.0F);
        com2.setAlignmentY(0.0F);

        com1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        com1.setAlignmentX(0.0F);
        com1.setAlignmentY(0.0F);
        com1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com1ActionPerformed(evt);
            }
        });

        txtt.setEnabled(false);

        group3.add(radio6);
        radio6.setText("Panel");
        radio6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radio6FocusGained(evt);
            }
        });

        group3.add(radio7);
        radio7.setText("Non-Panel");
        radio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio7ActionPerformed(evt);
            }
        });
        radio7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                radio7FocusGained(evt);
            }
        });

        jLabel20.setText("Status :");

        jLabel22.setText("Doctor :");

        doc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Doctor", "Dr Andy", "Dr James", "Dr Candy", "Dr John", "Dr Jordan" }));
        doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docActionPerformed(evt);
            }
        });
        doc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                docFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(radio3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(radio4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(radio5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(com1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(com2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(com4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(radio1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(radio2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(txt_8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(40, 40, 40)
                                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(doc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txt_7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio6)
                                        .addGap(46, 46, 46)
                                        .addComponent(radio7))
                                    .addComponent(txt_9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(9, 9, 9)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(455, Short.MAX_VALUE)
                .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(506, 506, 506)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23)
                                    .addComponent(txt_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(com1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(com2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(com4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(radio1)
                                            .addComponent(radio2))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)
                                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(txt_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(radio3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radio4)
                                        .addComponent(radio5)))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(txt_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(txt_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel20)
                                            .addComponent(radio7)
                                            .addComponent(radio6)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(txt_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(doc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtt, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryActionPerformed
        // TODO add your handling code here:
     st=(String)country.getSelectedItem();
        

         if (country.getSelectedItem().equals("Pakistan")) {
             City.setModel(null);
            City.addItem("Karachi");
            City.addItem("Lahore");
            City.addItem("Islamabad");
            City.addItem("Peshawar");

        }
        else if (country.getSelectedItem().equals("America")) {
            City.addItem("California");
            City.addItem("Colorado");
            City.addItem("Florida");
            City.addItem("New Hampshire");
             City.addItem("New Jersey");
              City.addItem("Texas");

        }
        else  if (country.getSelectedItem().equals("Afghanistan")) {
            City.addItem("Kabul");
            City.addItem("Ghazni");
            City.addItem("Balkh");
            City.addItem("Jalalabad");
             City.addItem("Kandahar");
              City.addItem("Lashkar Gah");

        }
        else  if (country.getSelectedItem().equals("Bangladesh")) {
            City.addItem("Barisal");
            City.addItem("Chittagong");
            City.addItem("Sylhet");
            City.addItem("Dhaka");
             City.addItem("Rangpur");
              City.addItem("Rajshahi");

        }
        else if (country.getSelectedItem().equals("Bangladesh")) {
           
            City.addItem("Barisal");
            City.addItem("Chittagong");
            City.addItem("Sylhet");
            City.addItem("Dhaka");
             City.addItem("Rangpur");
              City.addItem("Rajshahi");

        }
          else if (country.getSelectedItem().equals("Canada")) {
           
            City.addItem("Edmonton");
            City.addItem("Ottawa");
            City.addItem("Victoria");
            City.addItem("Toronto");
             City.addItem("Charlottetown");
              City.addItem("Whitehorse");

        }
          else if (country.getSelectedItem().equals("India")) {
          City.setVisible(true);
            City.addItem("Agra");
            City.addItem("Ahmedabad");
            City.addItem("Rajasthan");
            City.addItem("Chandigarh");
             City.addItem("Delhi");
              City.addItem("Goa");

        }
         String s1=(String)country.getSelectedItem();
       b=s1;
       txt2.setText(b);

          
            
}//GEN-LAST:event_countryActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("sun.jdbc.odbc.JdbcOdbc");
            Connection con=DriverManager.getConnection("jdbc:odbc:db","sa","aptech");
            java.sql.Statement s=con.createStatement();

             String c1=(String) com1.getSelectedItem();
             String c2=(String) com2.getSelectedItem();
             String c3=(String) com4.getSelectedItem();
             st1=(String) doc.getSelectedItem();

             txtt.setText(c1+"-"+c2+"-"+c3);

             

            if(txt_4.getText().length()==0 || txt_4.getText().equals("Numbers Only") ||txt_4.getText().equalsIgnoreCase("Insert ID")||txt_4.getText().equalsIgnoreCase("Numbers Only"))
            {
                  txt_4.setForeground(Color.red);
                   txt_4.setText("Insert ID");
            JOptionPane.showMessageDialog(rootPane,"Please Insert ID !!!");
             }
             else  if(txt_5.getText().length()==0 || txt_5.getText().equals("Text Only") ||txt_5.getText().equalsIgnoreCase("Insert Prefix") ||txt_5.getText().equalsIgnoreCase("Text Only"))
            {
                 txt_5.setForeground(Color.red);
                   txt_5.setText("Insert Prefix");
            JOptionPane.showMessageDialog(rootPane,"Please Insert Prefix !!!");
            }
             else  if(txt_1.getText().length()==0 || txt_1.getText().equals("Text Only")||txt_1.getText().equalsIgnoreCase("Insert Name")||txt_1.getText().equalsIgnoreCase("Text Only"))
            {
                 txt_1.setForeground(Color.red);
                   txt_1.setText("Insert Name");
            JOptionPane.showMessageDialog(rootPane,"Please Insert Name !!!");
            }
             else  if(txt_3.getText().length()==0 || txt_3.getText().equals("Text Only")||txt_3.getText().equalsIgnoreCase("Insert Last Name")||txt_3.getText().equalsIgnoreCase("Text Only"))
            {
                 txt_3.setForeground(Color.red);
                   txt_3.setText("Insert Last Name");
            JOptionPane.showMessageDialog(rootPane,"Please Insert Last Name !!!");
            }
             else  if(radio1.isSelected()==false && radio2.isSelected()==false)
            {
                 radio1.setForeground(Color.red);
                 radio2.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane,"Please Select Gender !!!");
            }
             else  if(country.getSelectedIndex()==0 )
            {
                 country.setForeground(Color.RED);
            JOptionPane.showMessageDialog(rootPane,"Please Select Country !!!");
            }

              else  if(City.getSelectedIndex()==0 )
            {
                   City.setForeground(Color.RED);
            JOptionPane.showMessageDialog(rootPane,"Please Select City !!!");
            }
             
              else  if(txt_6.getText().length()==0 || txt_6.getText().equalsIgnoreCase("Insert Address")||txt_6.getText().equalsIgnoreCase("Text Only"))
            {
                 txt_6.setForeground(Color.red);
                   txt_6.setText("Insert Address");
            JOptionPane.showMessageDialog(rootPane,"Please Insert Address !!!");
            }
             else  if(radio3.isSelected()==false && radio4.isSelected()==false && radio5.isSelected()==false)
            {
                 radio3.setForeground(Color.red);
                 radio4.setForeground(Color.red);
                  radio5.setForeground(Color.red);
                  // txt_6.setText("Insert Address");
            JOptionPane.showMessageDialog(rootPane,"Please Select Patient Maritial Status ");
            }

              else if (radio1.getText().equals(null) && radio4.getText().equals(null)&&radio5.getText().equals(null)) {
             JOptionPane.showMessageDialog(rootPane, "Please Select Patient Status !!!");
            }
              else  if(txt_7.getText().length()==0 ||txt_7.getText().equals("Numbers Only")|| txt_7.getText().equalsIgnoreCase("Insert Phone Number")||txt_7.getText().equalsIgnoreCase("Numbers Only"))
            {
                 txt_7.setForeground(Color.red);
                   txt_7.setText("Insert Phone Number");
            JOptionPane.showMessageDialog(rootPane,"Please Insert Phone Number !!!");
            }
              else  if(txt_8.getText().length()==0 ||txt_8.getText().equals("Numbers Only")|| txt_8.getText().equalsIgnoreCase("Insert Mobile Number")||txt_7.getText().equalsIgnoreCase("Numbers Only"))
            {
                 txt_8.setForeground(Color.red);
                   txt_8.setText("Insert Mobile Number");
            JOptionPane.showMessageDialog(rootPane,"Please Insert Mobile Number !!!");
            }
             else  if(txt_9.getText().length()==0 ||txt_9.getText().equals("Insert Email")|| txt_9.getText().equals("Invalid ID"))
            {
                 txt_9.setForeground(Color.red);
                   txt_9.setText("Insert Email");
            JOptionPane.showMessageDialog(rootPane,"Please Insert Email !!!");
            }
            else  if(doc.getSelectedIndex()==0 )
            {
                doc.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane,"Please Select Doctor !!! ");
            }

            else  if(radio6.isSelected()==false && radio7.isSelected()==false )
            {
               radio6.setForeground(Color.red);
               radio7.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane,"Please Select Patient Panel Status !!!");
            }
             else{
            if(radio1.isSelected()){
                radiotext=radio1.getText();

            }
          if(radio2.isSelected()){
                radiotext=radio2.getText();

            }

            if(radio3.isSelected()){
                radiotext2=radio3.getText();

            }
          if(radio4.isSelected()){
                radiotext2=radio4.getText();

            }
            if(radio5.isSelected()){
                radiotext2=radio5.getText();

            }
            if(radio6.isSelected()){
                radiotext3=radio6.getText();

            }
            if(radio7.isSelected()){
                radiotext3=radio7.getText();

            }
            // country.setSelectedIndex(0);
      //  City.setSelectedIndex(0);
       
            s.execute("insert into patient values('"+txt_4.getText()+"','"+txt_5.getText()+"','"+txt_1.getText()+"','"+txt_3.getText()+"','"+txtt.getText()+"','"+radiotext+"','"+st+"','"+str+"','"+txt_6.getText()+"','"+radiotext2+"','"+txt_7.getText()+"','"+txt_8.getText()+"','"+txt_9.getText()+"','"+st1+"','"+radiotext3+"')");
            JOptionPane.showMessageDialog(rootPane, "Record Inserted Successfully!!");
             }
        } catch(SQLException ex){
                  JOptionPane.showMessageDialog(rootPane, "Error!!! " + ex );
             }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error!!! " + e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:.
   str=(String)City.getSelectedItem();
    }//GEN-LAST:event_CityActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
         String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Continue ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

          one o=new one();
        o.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
             one o=new one();
        o.setVisible(true);
        this.dispose();
    }
        
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
           String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Continue ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

          two a=new two();
        a.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
               two a=new two();
        a.setVisible(true);
        this.dispose();
   }
        
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
         String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Continue ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

          three t=new three();
        t.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
             three t=new three();
        t.setVisible(true);
        this.dispose();
    }
        
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
         String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Continue ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

          four f=new four();
        f.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
                 four f=new four();
        f.setVisible(true);
        this.dispose();
    }
        
    }//GEN-LAST:event_txt6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Continue ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

         five f=new five();
        f.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
                 five f=new five();
        f.setVisible(true);
        this.dispose();
    }

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
            String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Continue ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

          six t=new six();
        t.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
                six t=new six();
        t.setVisible(true);
        this.dispose();
   }
      
    }//GEN-LAST:event_txt5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Continue ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

           seven t=new seven();
        t.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
                seven t=new seven();
        t.setVisible(true);
        this.dispose();
    }

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jLabel5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel5PropertyChange
        // TODO add your handling code here:
        jLabel5.setText(""+ date1);
    }//GEN-LAST:event_jLabel5PropertyChange

    private void txt_4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_4FocusLost
        // TODO add your handling code here:
        String exp="[0-9]*";
String st1=txt_4.getText();
String pat=Pattern.compile(exp).toString();
if(st1.matches(pat)==true){
    txt_4.setForeground(Color.BLACK);
   }
 else{
       txt_4.setForeground(Color.red);
       txt_4.setText("Numbers Only");
   }
    }//GEN-LAST:event_txt_4FocusLost

    private void txt_7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_7FocusLost
        // TODO add your handling code here:
        String exp="[0-9]*";
String st1=txt_7.getText();
String pat=Pattern.compile(exp).toString();
if(st1.matches(pat)==true){
    txt_7.setForeground(Color.BLACK);
   }
 else{
       txt_7.setForeground(Color.red);
       txt_7.setText("Numbers Only");
   }
    }//GEN-LAST:event_txt_7FocusLost

    private void txt_8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_8FocusLost
        // TODO add your handling code here:
        String exp="[0-9]*";
String st1=txt_8.getText();
String pat=Pattern.compile(exp).toString();
if(st1.matches(pat)==true){
    txt_8.setForeground(Color.BLACK);
   }
 else{
       txt_8.setForeground(Color.red);
       txt_8.setText("Numbers Only");
   }
    }//GEN-LAST:event_txt_8FocusLost

    private void txt_5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_5FocusLost
        // TODO add your handling code here:
        String exp="[a-zA-Z]*+||([a-zA-Z]*\\s[a-zA-Z]*)+||([a-zA-Z]*\\s[a-zA-Z]*\\s[a-zA-Z]*)";
String s1=txt_5.getText();
String pat=Pattern.compile(exp).toString();
if(s1.matches(pat)==true){
    txt_5.setForeground(Color.BLACK);
   }
 else{
       txt_5.setForeground(Color.red);
       txt_5.setText("Text Only");
   }
    }//GEN-LAST:event_txt_5FocusLost

    private void txt_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_1FocusLost
        // TODO add your handling code here:
        String exp="[a-zA-Z]*+||([a-zA-Z]*\\s[a-zA-Z]*)+||([a-zA-Z]*\\s[a-zA-Z]*\\s[a-zA-Z]*)";
String s1=txt_1.getText();
String pat=Pattern.compile(exp).toString();
if(s1.matches(pat)==true){
    txt_1.setForeground(Color.BLACK);
   }
 else{
       txt_1.setForeground(Color.red);
       txt_1.setText("Text Only");
   }
    }//GEN-LAST:event_txt_1FocusLost

    private void txt_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_3FocusLost
        // TODO add your handling code here:
        String exp="[a-zA-Z]*+||([a-zA-Z]*\\s[a-zA-Z]*)+||([a-zA-Z]*\\s[a-zA-Z]*\\s[a-zA-Z]*)";
String s1=txt_3.getText();
String pat=Pattern.compile(exp).toString();
if(s1.matches(pat)==true){
    txt_3.setForeground(Color.BLACK);
   }
 else{
       txt_3.setForeground(Color.red);
       txt_3.setText("Text Only");
   }
    }//GEN-LAST:event_txt_3FocusLost

    private void txt_9FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_9FocusLost
        // TODO add your handling code here:
         if(txt_9.getText().length()==0 ||txt_8.getText().equals("Insert Email")|| txt_8.getText().equals("Invalid ID"))
{
    txt_9.setForeground(Color.red);
    txt_9.setText("Insert Email");
}
else
{
String exp=".+@.+\\.[a-zA-Z]{2,4}+";
String s1=txt_9.getText();
String pat=Pattern.compile(exp).toString();
if(s1.matches(pat)==true){
    txt_9.setForeground(Color.BLACK);
   }
 else{
       txt_9.setForeground(Color.red);
       txt_9.setText("Invalid ID");
   }
}
    }//GEN-LAST:event_txt_9FocusLost

    private void txt_4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_4FocusGained
        // TODO add your handling code here:
        if(txt_4.getText().equalsIgnoreCase("Insert ID")||txt_4.getText().equalsIgnoreCase("Numbers Only"))
    {   txt_4.setForeground(Color.BLACK);
         txt_4.setText("");
    }
else
{

}
       
    }//GEN-LAST:event_txt_4FocusGained

    private void txt_5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_5FocusGained
        // TODO add your handling code here:
       if(txt_5.getText().equalsIgnoreCase("Text Only")|| txt_5.getText().equals("Text Only") ||txt_5.getText().equalsIgnoreCase("Insert Prefix") ||txt_5.getText().equalsIgnoreCase("Text Only"))
    {   txt_5.setForeground(Color.BLACK);
         txt_5.setText("");
    }
    }//GEN-LAST:event_txt_5FocusGained

    private void txt_1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_1FocusGained
        // TODO add your handling code here:
        if(txt_1.getText().equalsIgnoreCase("Insert Name")||txt_1.getText().equalsIgnoreCase("Text Only"))
    {   txt_1.setForeground(Color.BLACK);
         txt_1.setText("");
    }
    }//GEN-LAST:event_txt_1FocusGained

    private void txt_3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_3FocusGained
        // TODO add your handling code here:
        if(txt_3.getText().equalsIgnoreCase("Insert Last Name")||txt_3.getText().equalsIgnoreCase("Text Only"))
    {   txt_3.setForeground(Color.BLACK);
         txt_3.setText("");
    }
    }//GEN-LAST:event_txt_3FocusGained

    private void txt_6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_6FocusGained
        // TODO add your handling code here:
        if(txt_6.getText().equalsIgnoreCase("Insert Address")||txt_6.getText().equalsIgnoreCase("Text Only"))
    {   txt_6.setForeground(Color.BLACK);
         txt_6.setText("");
    }
    }//GEN-LAST:event_txt_6FocusGained

    private void txt_7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_7FocusGained
        // TODO add your handling code here:
        if(txt_7.getText().equalsIgnoreCase("Insert Phone Number")||txt_7.getText().equalsIgnoreCase("Numbers Only"))
    {   txt_7.setForeground(Color.BLACK);
         txt_7.setText("");
    }
    }//GEN-LAST:event_txt_7FocusGained

    private void txt_8FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_8FocusGained
        // TODO add your handling code here:
        if(txt_8.getText().equalsIgnoreCase("Insert Mobile Number")||txt_8.getText().equalsIgnoreCase("Numbers Only"))
    {   txt_8.setForeground(Color.BLACK);
         txt_8.setText("");
    }
    }//GEN-LAST:event_txt_8FocusGained

    private void txt_9FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_9FocusGained
        // TODO add your handling code here:
        if(txt_9.getText().equals("Insert Email")||txt_9.getText().equals("Invalid ID"))
    {   txt_9.setForeground(Color.BLACK);
         txt_9.setText("");
    }
    }//GEN-LAST:event_txt_9FocusGained

    private void com1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_com1ActionPerformed

    private void countryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_countryFocusGained
        // TODO add your handling code here:
        country.setForeground(Color.black);
       
    }//GEN-LAST:event_countryFocusGained

    private void txt_6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_6FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_6FocusLost

    private void radio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio7ActionPerformed

    private void docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docActionPerformed
        // TODO add your handling code here:
        st1=(String) doc.getSelectedItem();
}//GEN-LAST:event_docActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String s1=txt_4.getText(),s2=txt5.getText(),s3=txt1.getText(),s4=txt2.getText(),s5=txt3.getText(),s6=txt6.getText();
    if (s1.length()!=0 || s2.length()!=0 || s3.length()!=0 || s4.length()!=0 || s5.length()!=0 || s6.length()!=0) {
     int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Exit ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

           this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    }
    else{
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void radio3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio3FocusGained
        // TODO add your handling code here:
        radio3.setForeground(Color.black);
                 radio4.setForeground(Color.black);
                  radio5.setForeground(Color.black);
    }//GEN-LAST:event_radio3FocusGained

    private void radio4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio4FocusGained
        // TODO add your handling code here:
     radio3.setForeground(Color.black);
                 radio4.setForeground(Color.black);
                  radio5.setForeground(Color.black);
    }//GEN-LAST:event_radio4FocusGained

    private void radio5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio5FocusGained
        // TODO add your handling code here:
    radio3.setForeground(Color.black);
                 radio4.setForeground(Color.black);
                  radio5.setForeground(Color.black);
    }//GEN-LAST:event_radio5FocusGained

    private void docFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_docFocusGained
        // TODO add your handling code here:
        doc.setForeground(Color.black);
    }//GEN-LAST:event_docFocusGained

    private void radio1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio1FocusGained
        // TODO add your handling code here:
        radio1.setForeground(Color.black);
          radio2.setForeground(Color.black);
    }//GEN-LAST:event_radio1FocusGained

    private void radio2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio2FocusGained
        // TODO add your handling code here:
         radio1.setForeground(Color.black);
       radio2.setForeground(Color.black);
    }//GEN-LAST:event_radio2FocusGained

    private void CityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityFocusGained
        // TODO add your handling code here:
        City.setForeground(Color.black);
    }//GEN-LAST:event_CityFocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         int b=JOptionPane.showConfirmDialog(rootPane, "Do You Want to Logout ?","New",JOptionPane.YES_NO_OPTION);
   if(b==JOptionPane.YES_OPTION)
           {

           Login t=new Login();
        t.setVisible(true);
        this.dispose();
           }
     if(b==JOptionPane.NO_OPTION)
           {
//System.nanoTime();

           }
    
    else{
  }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void radio7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio7FocusGained
        // TODO add your handling code here:
        radio6.setForeground(Color.black);
                 radio7.setForeground(Color.black);

    }//GEN-LAST:event_radio7FocusGained

    private void radio6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio6FocusGained
        // TODO add your handling code here:
        radio6.setForeground(Color.black);
                 radio7.setForeground(Color.black);
    }//GEN-LAST:event_radio6FocusGained

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addpatient().setVisible(true);
            }
        });

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox City;
    private javax.swing.JComboBox com1;
    private javax.swing.JComboBox com2;
    private javax.swing.JComboBox com4;
    private javax.swing.JComboBox country;
    private javax.swing.JComboBox doc;
    private javax.swing.ButtonGroup group;
    private javax.swing.ButtonGroup group2;
    private javax.swing.ButtonGroup group3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JRadioButton radio6;
    private javax.swing.JRadioButton radio7;
    private javax.swing.JButton txt1;
    private javax.swing.JButton txt2;
    private javax.swing.JButton txt3;
    private javax.swing.JButton txt5;
    private javax.swing.JButton txt6;
    private javax.swing.JTextField txt_1;
    private javax.swing.JTextField txt_3;
    private javax.swing.JTextField txt_4;
    private javax.swing.JTextField txt_5;
    private javax.swing.JTextField txt_6;
    private javax.swing.JTextField txt_7;
    private javax.swing.JTextField txt_8;
    private javax.swing.JTextField txt_9;
    private javax.swing.JTextField txtt;
    // End of variables declaration//GEN-END:variables

}
